<?php

return [
    4 => ['id' => 4, 'alpha2' => 'af', 'alpha3' => 'afg', 'name' => 'Afghanistan'],
    710 => ['id' => 710, 'alpha2' => 'za', 'alpha3' => 'zaf', 'name' => 'Afrique du Sud'],
    8 => ['id' => 8, 'alpha2' => 'al', 'alpha3' => 'alb', 'name' => 'Albanie'],
    12 => ['id' => 12, 'alpha2' => 'dz', 'alpha3' => 'dza', 'name' => 'Algérie'],
    276 => ['id' => 276, 'alpha2' => 'de', 'alpha3' => 'deu', 'name' => 'Allemagne'],
    20 => ['id' => 20, 'alpha2' => 'ad', 'alpha3' => 'and', 'name' => 'Andorre'],
    24 => ['id' => 24, 'alpha2' => 'ao', 'alpha3' => 'ago', 'name' => 'Angola'],
    28 => ['id' => 28, 'alpha2' => 'ag', 'alpha3' => 'atg', 'name' => 'Antigua-et-Barbuda'],
    682 => ['id' => 682, 'alpha2' => 'sa', 'alpha3' => 'sau', 'name' => 'Arabie saoudite'],
    32 => ['id' => 32, 'alpha2' => 'ar', 'alpha3' => 'arg', 'name' => 'Argentine'],
    51 => ['id' => 51, 'alpha2' => 'am', 'alpha3' => 'arm', 'name' => 'Arménie'],
    36 => ['id' => 36, 'alpha2' => 'au', 'alpha3' => 'aus', 'name' => 'Australie'],
    40 => ['id' => 40, 'alpha2' => 'at', 'alpha3' => 'aut', 'name' => 'Autriche'],
    31 => ['id' => 31, 'alpha2' => 'az', 'alpha3' => 'aze', 'name' => 'Azerbaïdjan'],
    44 => ['id' => 44, 'alpha2' => 'bs', 'alpha3' => 'bhs', 'name' => 'Bahamas'],
    48 => ['id' => 48, 'alpha2' => 'bh', 'alpha3' => 'bhr', 'name' => 'Bahreïn'],
    50 => ['id' => 50, 'alpha2' => 'bd', 'alpha3' => 'bgd', 'name' => 'Bangladesh'],
    52 => ['id' => 52, 'alpha2' => 'bb', 'alpha3' => 'brb', 'name' => 'Barbade'],
    112 => ['id' => 112, 'alpha2' => 'by', 'alpha3' => 'blr', 'name' => 'Biélorussie'],
    56 => ['id' => 56, 'alpha2' => 'be', 'alpha3' => 'bel', 'name' => 'Belgique'],
    84 => ['id' => 84, 'alpha2' => 'bz', 'alpha3' => 'blz', 'name' => 'Belize'],
    204 => ['id' => 204, 'alpha2' => 'bj', 'alpha3' => 'ben', 'name' => 'Bénin'],
    64 => ['id' => 64, 'alpha2' => 'bt', 'alpha3' => 'btn', 'name' => 'Bhoutan'],
    68 => ['id' => 68, 'alpha2' => 'bo', 'alpha3' => 'bol', 'name' => 'Bolivie'],
    70 => ['id' => 70, 'alpha2' => 'ba', 'alpha3' => 'bih', 'name' => 'Bosnie-Herzégovine'],
    72 => ['id' => 72, 'alpha2' => 'bw', 'alpha3' => 'bwa', 'name' => 'Botswana'],
    76 => ['id' => 76, 'alpha2' => 'br', 'alpha3' => 'bra', 'name' => 'Brésil'],
    96 => ['id' => 96, 'alpha2' => 'bn', 'alpha3' => 'brn', 'name' => 'Brunei'],
    100 => ['id' => 100, 'alpha2' => 'bg', 'alpha3' => 'bgr', 'name' => 'Bulgarie'],
    854 => ['id' => 854, 'alpha2' => 'bf', 'alpha3' => 'bfa', 'name' => 'Burkina Faso'],
    108 => ['id' => 108, 'alpha2' => 'bi', 'alpha3' => 'bdi', 'name' => 'Burundi'],
    116 => ['id' => 116, 'alpha2' => 'kh', 'alpha3' => 'khm', 'name' => 'Cambodge'],
    120 => ['id' => 120, 'alpha2' => 'cm', 'alpha3' => 'cmr', 'name' => 'Cameroun'],
    124 => ['id' => 124, 'alpha2' => 'ca', 'alpha3' => 'can', 'name' => 'Canada'],
    132 => ['id' => 132, 'alpha2' => 'cv', 'alpha3' => 'cpv', 'name' => 'Cap-Vert'],
    140 => ['id' => 140, 'alpha2' => 'cf', 'alpha3' => 'caf', 'name' => 'République centrafricaine'],
    152 => ['id' => 152, 'alpha2' => 'cl', 'alpha3' => 'chl', 'name' => 'Chili'],
    156 => ['id' => 156, 'alpha2' => 'cn', 'alpha3' => 'chn', 'name' => 'Chine'],
    196 => ['id' => 196, 'alpha2' => 'cy', 'alpha3' => 'cyp', 'name' => 'Chypre'],
    170 => ['id' => 170, 'alpha2' => 'co', 'alpha3' => 'col', 'name' => 'Colombie'],
    174 => ['id' => 174, 'alpha2' => 'km', 'alpha3' => 'com', 'name' => 'Comores'],
    178 => ['id' => 178, 'alpha2' => 'cg', 'alpha3' => 'cog', 'name' => 'République du Congo'],
    180 => ['id' => 180, 'alpha2' => 'cd', 'alpha3' => 'cod', 'name' => 'République démocratique du Congo'],
    410 => ['id' => 410, 'alpha2' => 'kr', 'alpha3' => 'kor', 'name' => 'Corée du Sud'],
    408 => ['id' => 408, 'alpha2' => 'kp', 'alpha3' => 'prk', 'name' => 'Corée du Nord'],
    188 => ['id' => 188, 'alpha2' => 'cr', 'alpha3' => 'cri', 'name' => 'Costa Rica'],
    384 => ['id' => 384, 'alpha2' => 'ci', 'alpha3' => 'civ', 'name' => 'Côte d\'Ivoire'],
    191 => ['id' => 191, 'alpha2' => 'hr', 'alpha3' => 'hrv', 'name' => 'Croatie'],
    192 => ['id' => 192, 'alpha2' => 'cu', 'alpha3' => 'cub', 'name' => 'Cuba'],
    208 => ['id' => 208, 'alpha2' => 'dk', 'alpha3' => 'dnk', 'name' => 'Danemark'],
    262 => ['id' => 262, 'alpha2' => 'dj', 'alpha3' => 'dji', 'name' => 'Djibouti'],
    214 => ['id' => 214, 'alpha2' => 'do', 'alpha3' => 'dom', 'name' => 'République dominicaine'],
    212 => ['id' => 212, 'alpha2' => 'dm', 'alpha3' => 'dma', 'name' => 'Dominique'],
    818 => ['id' => 818, 'alpha2' => 'eg', 'alpha3' => 'egy', 'name' => 'Égypte'],
    222 => ['id' => 222, 'alpha2' => 'sv', 'alpha3' => 'slv', 'name' => 'Salvador'],
    784 => ['id' => 784, 'alpha2' => 'ae', 'alpha3' => 'are', 'name' => 'Émirats arabes unis'],
    218 => ['id' => 218, 'alpha2' => 'ec', 'alpha3' => 'ecu', 'name' => 'Équateur'],
    232 => ['id' => 232, 'alpha2' => 'er', 'alpha3' => 'eri', 'name' => 'Érythrée'],
    724 => ['id' => 724, 'alpha2' => 'es', 'alpha3' => 'esp', 'name' => 'Espagne'],
    233 => ['id' => 233, 'alpha2' => 'ee', 'alpha3' => 'est', 'name' => 'Estonie'],
    840 => ['id' => 840, 'alpha2' => 'us', 'alpha3' => 'usa', 'name' => 'États-Unis'],
    231 => ['id' => 231, 'alpha2' => 'et', 'alpha3' => 'eth', 'name' => 'Éthiopie'],
    242 => ['id' => 242, 'alpha2' => 'fj', 'alpha3' => 'fji', 'name' => 'Fidji'],
    246 => ['id' => 246, 'alpha2' => 'fi', 'alpha3' => 'fin', 'name' => 'Finlande'],
    250 => ['id' => 250, 'alpha2' => 'fr', 'alpha3' => 'fra', 'name' => 'France'],
    266 => ['id' => 266, 'alpha2' => 'ga', 'alpha3' => 'gab', 'name' => 'Gabon'],
    270 => ['id' => 270, 'alpha2' => 'gm', 'alpha3' => 'gmb', 'name' => 'Gambie'],
    268 => ['id' => 268, 'alpha2' => 'ge', 'alpha3' => 'geo', 'name' => 'Géorgie'],
    288 => ['id' => 288, 'alpha2' => 'gh', 'alpha3' => 'gha', 'name' => 'Ghana'],
    300 => ['id' => 300, 'alpha2' => 'gr', 'alpha3' => 'grc', 'name' => 'Grèce'],
    308 => ['id' => 308, 'alpha2' => 'gd', 'alpha3' => 'grd', 'name' => 'Grenade'],
    320 => ['id' => 320, 'alpha2' => 'gt', 'alpha3' => 'gtm', 'name' => 'Guatemala'],
    324 => ['id' => 324, 'alpha2' => 'gn', 'alpha3' => 'gin', 'name' => 'Guinée'],
    624 => ['id' => 624, 'alpha2' => 'gw', 'alpha3' => 'gnb', 'name' => 'Guinée-Bissau'],
    226 => ['id' => 226, 'alpha2' => 'gq', 'alpha3' => 'gnq', 'name' => 'Guinée équatoriale'],
    328 => ['id' => 328, 'alpha2' => 'gy', 'alpha3' => 'guy', 'name' => 'Guyana'],
    332 => ['id' => 332, 'alpha2' => 'ht', 'alpha3' => 'hti', 'name' => 'Haïti'],
    340 => ['id' => 340, 'alpha2' => 'hn', 'alpha3' => 'hnd', 'name' => 'Honduras'],
    348 => ['id' => 348, 'alpha2' => 'hu', 'alpha3' => 'hun', 'name' => 'Hongrie'],
    356 => ['id' => 356, 'alpha2' => 'in', 'alpha3' => 'ind', 'name' => 'Inde'],
    360 => ['id' => 360, 'alpha2' => 'id', 'alpha3' => 'idn', 'name' => 'Indonésie'],
    364 => ['id' => 364, 'alpha2' => 'ir', 'alpha3' => 'irn', 'name' => 'Iran'],
    368 => ['id' => 368, 'alpha2' => 'iq', 'alpha3' => 'irq', 'name' => 'Irak'],
    372 => ['id' => 372, 'alpha2' => 'ie', 'alpha3' => 'irl', 'name' => 'Irlande'],
    352 => ['id' => 352, 'alpha2' => 'is', 'alpha3' => 'isl', 'name' => 'Islande'],
    376 => ['id' => 376, 'alpha2' => 'il', 'alpha3' => 'isr', 'name' => 'Israël'],
    380 => ['id' => 380, 'alpha2' => 'it', 'alpha3' => 'ita', 'name' => 'Italie'],
    388 => ['id' => 388, 'alpha2' => 'jm', 'alpha3' => 'jam', 'name' => 'Jamaïque'],
    392 => ['id' => 392, 'alpha2' => 'jp', 'alpha3' => 'jpn', 'name' => 'Japon'],
    400 => ['id' => 400, 'alpha2' => 'jo', 'alpha3' => 'jor', 'name' => 'Jordanie'],
    398 => ['id' => 398, 'alpha2' => 'kz', 'alpha3' => 'kaz', 'name' => 'Kazakhstan'],
    404 => ['id' => 404, 'alpha2' => 'ke', 'alpha3' => 'ken', 'name' => 'Kenya'],
    417 => ['id' => 417, 'alpha2' => 'kg', 'alpha3' => 'kgz', 'name' => 'Kirghizistan'],
    296 => ['id' => 296, 'alpha2' => 'ki', 'alpha3' => 'kir', 'name' => 'Kiribati'],
    414 => ['id' => 414, 'alpha2' => 'kw', 'alpha3' => 'kwt', 'name' => 'Koweït'],
    418 => ['id' => 418, 'alpha2' => 'la', 'alpha3' => 'lao', 'name' => 'Laos'],
    426 => ['id' => 426, 'alpha2' => 'ls', 'alpha3' => 'lso', 'name' => 'Lesotho'],
    428 => ['id' => 428, 'alpha2' => 'lv', 'alpha3' => 'lva', 'name' => 'Lettonie'],
    422 => ['id' => 422, 'alpha2' => 'lb', 'alpha3' => 'lbn', 'name' => 'Liban'],
    430 => ['id' => 430, 'alpha2' => 'lr', 'alpha3' => 'lbr', 'name' => 'Liberia'],
    434 => ['id' => 434, 'alpha2' => 'ly', 'alpha3' => 'lby', 'name' => 'Libye'],
    438 => ['id' => 438, 'alpha2' => 'li', 'alpha3' => 'lie', 'name' => 'Liechtenstein'],
    440 => ['id' => 440, 'alpha2' => 'lt', 'alpha3' => 'ltu', 'name' => 'Lituanie'],
    442 => ['id' => 442, 'alpha2' => 'lu', 'alpha3' => 'lux', 'name' => 'Luxembourg'],
    807 => ['id' => 807, 'alpha2' => 'mk', 'alpha3' => 'mkd', 'name' => 'Macédoine du Nord'],
    450 => ['id' => 450, 'alpha2' => 'mg', 'alpha3' => 'mdg', 'name' => 'Madagascar'],
    458 => ['id' => 458, 'alpha2' => 'my', 'alpha3' => 'mys', 'name' => 'Malaisie'],
    454 => ['id' => 454, 'alpha2' => 'mw', 'alpha3' => 'mwi', 'name' => 'Malawi'],
    462 => ['id' => 462, 'alpha2' => 'mv', 'alpha3' => 'mdv', 'name' => 'Maldives'],
    466 => ['id' => 466, 'alpha2' => 'ml', 'alpha3' => 'mli', 'name' => 'Mali'],
    470 => ['id' => 470, 'alpha2' => 'mt', 'alpha3' => 'mlt', 'name' => 'Malte'],
    504 => ['id' => 504, 'alpha2' => 'ma', 'alpha3' => 'mar', 'name' => 'Maroc'],
    584 => ['id' => 584, 'alpha2' => 'mh', 'alpha3' => 'mhl', 'name' => 'Îles Marshall'],
    480 => ['id' => 480, 'alpha2' => 'mu', 'alpha3' => 'mus', 'name' => 'Maurice'],
    478 => ['id' => 478, 'alpha2' => 'mr', 'alpha3' => 'mrt', 'name' => 'Mauritanie'],
    484 => ['id' => 484, 'alpha2' => 'mx', 'alpha3' => 'mex', 'name' => 'Mexique'],
    583 => ['id' => 583, 'alpha2' => 'fm', 'alpha3' => 'fsm', 'name' => 'États fédérés de Micronésie'],
    498 => ['id' => 498, 'alpha2' => 'md', 'alpha3' => 'mda', 'name' => 'Moldavie'],
    492 => ['id' => 492, 'alpha2' => 'mc', 'alpha3' => 'mco', 'name' => 'Monaco'],
    496 => ['id' => 496, 'alpha2' => 'mn', 'alpha3' => 'mng', 'name' => 'Mongolie'],
    499 => ['id' => 499, 'alpha2' => 'me', 'alpha3' => 'mne', 'name' => 'Monténégro'],
    508 => ['id' => 508, 'alpha2' => 'mz', 'alpha3' => 'moz', 'name' => 'Mozambique'],
    104 => ['id' => 104, 'alpha2' => 'mm', 'alpha3' => 'mmr', 'name' => 'Birmanie'],
    516 => ['id' => 516, 'alpha2' => 'na', 'alpha3' => 'nam', 'name' => 'Namibie'],
    520 => ['id' => 520, 'alpha2' => 'nr', 'alpha3' => 'nru', 'name' => 'Nauru'],
    524 => ['id' => 524, 'alpha2' => 'np', 'alpha3' => 'npl', 'name' => 'Népal'],
    558 => ['id' => 558, 'alpha2' => 'ni', 'alpha3' => 'nic', 'name' => 'Nicaragua'],
    562 => ['id' => 562, 'alpha2' => 'ne', 'alpha3' => 'ner', 'name' => 'Niger'],
    566 => ['id' => 566, 'alpha2' => 'ng', 'alpha3' => 'nga', 'name' => 'Nigeria'],
    578 => ['id' => 578, 'alpha2' => 'no', 'alpha3' => 'nor', 'name' => 'Norvège'],
    554 => ['id' => 554, 'alpha2' => 'nz', 'alpha3' => 'nzl', 'name' => 'Nouvelle-Zélande'],
    512 => ['id' => 512, 'alpha2' => 'om', 'alpha3' => 'omn', 'name' => 'Oman'],
    800 => ['id' => 800, 'alpha2' => 'ug', 'alpha3' => 'uga', 'name' => 'Ouganda'],
    860 => ['id' => 860, 'alpha2' => 'uz', 'alpha3' => 'uzb', 'name' => 'Ouzbékistan'],
    586 => ['id' => 586, 'alpha2' => 'pk', 'alpha3' => 'pak', 'name' => 'Pakistan'],
    585 => ['id' => 585, 'alpha2' => 'pw', 'alpha3' => 'plw', 'name' => 'Palaos'],
    591 => ['id' => 591, 'alpha2' => 'pa', 'alpha3' => 'pan', 'name' => 'Panama'],
    598 => ['id' => 598, 'alpha2' => 'pg', 'alpha3' => 'png', 'name' => 'Papouasie-Nouvelle-Guinée'],
    600 => ['id' => 600, 'alpha2' => 'py', 'alpha3' => 'pry', 'name' => 'Paraguay'],
    528 => ['id' => 528, 'alpha2' => 'nl', 'alpha3' => 'nld', 'name' => 'Pays-Bas'],
    604 => ['id' => 604, 'alpha2' => 'pe', 'alpha3' => 'per', 'name' => 'Pérou'],
    608 => ['id' => 608, 'alpha2' => 'ph', 'alpha3' => 'phl', 'name' => 'Philippines'],
    616 => ['id' => 616, 'alpha2' => 'pl', 'alpha3' => 'pol', 'name' => 'Pologne'],
    620 => ['id' => 620, 'alpha2' => 'pt', 'alpha3' => 'prt', 'name' => 'Portugal'],
    634 => ['id' => 634, 'alpha2' => 'qa', 'alpha3' => 'qat', 'name' => 'Qatar'],
    642 => ['id' => 642, 'alpha2' => 'ro', 'alpha3' => 'rou', 'name' => 'Roumanie'],
    826 => ['id' => 826, 'alpha2' => 'gb', 'alpha3' => 'gbr', 'name' => 'Royaume-Uni'],
    643 => ['id' => 643, 'alpha2' => 'ru', 'alpha3' => 'rus', 'name' => 'Russie'],
    646 => ['id' => 646, 'alpha2' => 'rw', 'alpha3' => 'rwa', 'name' => 'Rwanda'],
    659 => ['id' => 659, 'alpha2' => 'kn', 'alpha3' => 'kna', 'name' => 'Saint-Christophe-et-Niévès'],
    674 => ['id' => 674, 'alpha2' => 'sm', 'alpha3' => 'smr', 'name' => 'Saint-Marin'],
    670 => ['id' => 670, 'alpha2' => 'vc', 'alpha3' => 'vct', 'name' => 'Saint-Vincent-et-les-Grenadines'],
    662 => ['id' => 662, 'alpha2' => 'lc', 'alpha3' => 'lca', 'name' => 'Sainte-Lucie'],
    90 => ['id' => 90, 'alpha2' => 'sb', 'alpha3' => 'slb', 'name' => 'Îles Salomon'],
    882 => ['id' => 882, 'alpha2' => 'ws', 'alpha3' => 'wsm', 'name' => 'Samoa'],
    678 => ['id' => 678, 'alpha2' => 'st', 'alpha3' => 'stp', 'name' => 'Sao Tomé-et-Principe'],
    686 => ['id' => 686, 'alpha2' => 'sn', 'alpha3' => 'sen', 'name' => 'Sénégal'],
    688 => ['id' => 688, 'alpha2' => 'rs', 'alpha3' => 'srb', 'name' => 'Serbie'],
    690 => ['id' => 690, 'alpha2' => 'sc', 'alpha3' => 'syc', 'name' => 'Seychelles'],
    694 => ['id' => 694, 'alpha2' => 'sl', 'alpha3' => 'sle', 'name' => 'Sierra Leone'],
    702 => ['id' => 702, 'alpha2' => 'sg', 'alpha3' => 'sgp', 'name' => 'Singapour'],
    703 => ['id' => 703, 'alpha2' => 'sk', 'alpha3' => 'svk', 'name' => 'Slovaquie'],
    705 => ['id' => 705, 'alpha2' => 'si', 'alpha3' => 'svn', 'name' => 'Slovénie'],
    706 => ['id' => 706, 'alpha2' => 'so', 'alpha3' => 'som', 'name' => 'Somalie'],
    729 => ['id' => 729, 'alpha2' => 'sd', 'alpha3' => 'sdn', 'name' => 'Soudan'],
    728 => ['id' => 728, 'alpha2' => 'ss', 'alpha3' => 'ssd', 'name' => 'Soudan du Sud'],
    144 => ['id' => 144, 'alpha2' => 'lk', 'alpha3' => 'lka', 'name' => 'Sri Lanka'],
    752 => ['id' => 752, 'alpha2' => 'se', 'alpha3' => 'swe', 'name' => 'Suède'],
    756 => ['id' => 756, 'alpha2' => 'ch', 'alpha3' => 'che', 'name' => 'Suisse'],
    740 => ['id' => 740, 'alpha2' => 'sr', 'alpha3' => 'sur', 'name' => 'Suriname'],
    748 => ['id' => 748, 'alpha2' => 'sz', 'alpha3' => 'swz', 'name' => 'Eswatini'],
    760 => ['id' => 760, 'alpha2' => 'sy', 'alpha3' => 'syr', 'name' => 'Syrie'],
    762 => ['id' => 762, 'alpha2' => 'tj', 'alpha3' => 'tjk', 'name' => 'Tadjikistan'],
    834 => ['id' => 834, 'alpha2' => 'tz', 'alpha3' => 'tza', 'name' => 'Tanzanie'],
    148 => ['id' => 148, 'alpha2' => 'td', 'alpha3' => 'tcd', 'name' => 'Tchad'],
    203 => ['id' => 203, 'alpha2' => 'cz', 'alpha3' => 'cze', 'name' => 'Tchéquie'],
    764 => ['id' => 764, 'alpha2' => 'th', 'alpha3' => 'tha', 'name' => 'Thaïlande'],
    626 => ['id' => 626, 'alpha2' => 'tl', 'alpha3' => 'tls', 'name' => 'Timor oriental'],
    768 => ['id' => 768, 'alpha2' => 'tg', 'alpha3' => 'tgo', 'name' => 'Togo'],
    776 => ['id' => 776, 'alpha2' => 'to', 'alpha3' => 'ton', 'name' => 'Tonga'],
    780 => ['id' => 780, 'alpha2' => 'tt', 'alpha3' => 'tto', 'name' => 'Trinité-et-Tobago'],
    788 => ['id' => 788, 'alpha2' => 'tn', 'alpha3' => 'tun', 'name' => 'Tunisie'],
    795 => ['id' => 795, 'alpha2' => 'tm', 'alpha3' => 'tkm', 'name' => 'Turkménistan'],
    792 => ['id' => 792, 'alpha2' => 'tr', 'alpha3' => 'tur', 'name' => 'Turquie'],
    798 => ['id' => 798, 'alpha2' => 'tv', 'alpha3' => 'tuv', 'name' => 'Tuvalu'],
    804 => ['id' => 804, 'alpha2' => 'ua', 'alpha3' => 'ukr', 'name' => 'Ukraine'],
    858 => ['id' => 858, 'alpha2' => 'uy', 'alpha3' => 'ury', 'name' => 'Uruguay'],
    548 => ['id' => 548, 'alpha2' => 'vu', 'alpha3' => 'vut', 'name' => 'Vanuatu'],
    862 => ['id' => 862, 'alpha2' => 've', 'alpha3' => 'ven', 'name' => 'Venezuela'],
    704 => ['id' => 704, 'alpha2' => 'vn', 'alpha3' => 'vnm', 'name' => 'Viêt Nam'],
    887 => ['id' => 887, 'alpha2' => 'ye', 'alpha3' => 'yem', 'name' => 'Yémen'],
    894 => ['id' => 894, 'alpha2' => 'zm', 'alpha3' => 'zmb', 'name' => 'Zambie'],
    716 => ['id' => 716, 'alpha2' => 'zw', 'alpha3' => 'zwe', 'name' => 'Zimbabwe'],
];
